import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://griz-sports.web.app/lg');
  await page.getByRole('textbox', { name: 'Username (Required)' }).click();
  await page.getByRole('textbox', { name: 'Username (Required)' }).fill('teamleader');
  await page.getByRole('textbox', { name: 'Password (Required)' }).click();
  await page.getByRole('textbox', { name: 'Password (Required)' }).fill('piss');
  await page.getByRole('button', { name: 'Enter' }).click();
  await page.getByRole('button', { name: 'Previous page' }).click();
  await page.getByRole('button', { name: 'Griz Tennis vs. Idaho State,' }).click();
  await page.getByRole('banner').locator('div').nth(1).click();
  await page.getByLabel('Filter by sport:').selectOption('Basketball');
  await page.getByRole('button', { name: 'Previous page' }).click();
  await page.getByLabel('Filter by sport:').selectOption('Football');
  await page.getByRole('button', { name: 'March 2025' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Previous page' }).click();
  await page.getByRole('button', { name: 'November' }).click();
  await page.getByRole('button', { name: 'Griz Football Home vs. #4 UC' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('banner').locator('ion-title slot').click();
  await page.goto('https://griz-sports.web.app/lg');
  await page.getByRole('button', { name: 'Sign Up' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Username' }).locator('div').nth(1).click();
  await page.locator('#ion-input-2').fill('tester');
  await page.locator('#ion-input-3').click();
  await page.locator('#ion-input-3').fill('playwright');
  await page.locator('#ion-input-4').click();
  await page.locator('#ion-input-4').fill('test');
  await page.locator('#ion-input-5').click();
  await page.locator('#ion-input-5').fill('er');
  await page.locator('#ion-input-6').click();
  await page.locator('#ion-input-6').fill('test@gmail.com');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('textbox', { name: 'Username (Required)' }).click();
  await page.getByRole('textbox', { name: 'Username (Required)' }).fill('tester');
  await page.getByRole('textbox', { name: 'Username (Required)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password (Required)' }).fill('playwright');
  await page.getByRole('button', { name: 'Enter' }).click();
  await page.goto('https://griz-sports.web.app/lg');
});