name: CI Test Pipeline (Windows PowerShell)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use Windows as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Set up Node.js (for Ionic)
    - name: Set up Node.js (for Ionic)
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Step 2: Install dependencies for Ionic App
    - name: Install dependencies for Ionic app
      shell: pwsh
      run: |
        cd  ionic-griz-sports
        npm install

    # Step 3: Run Ionic Tests
    - name: Run Ionic Tests
      shell: pwsh
      run: |
        cd  ionic-griz-sports
        npm run test -- --watch=false --browsers=ChromeHeadless

    # Step 4: Set up Java (for Spring Boot)
    - name: Set up Java (for Spring Boot)
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Step 5: Set up Azure SQL Database Connection
    - name: Configure Azure SQL Database Connection
      shell: pwsh
      run: |
        echo "Setting up Azure SQL connection..."
        # Ensure environment variables contain the correct Azure SQL credentials
        $env:DB_SERVER = "your-azure-sql-server.database.windows.net"
        $env:DB_NAME = "your-database-name"
        $env:DB_USER = "your-db-user"
        $env:DB_PASSWORD = "your-db-password"

    # Step 6: Install dependencies for Spring Boot App
    - name: Install dependencies for Spring Boot app
      shell: pwsh
      run: |
        cd springboot-app
        ./mvnw install

    # Step 7: Run Spring Boot Tests
    - name: Run Spring Boot Tests
      shell: pwsh
      run: |
        cd springboot-app
        ./mvnw test
